#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DbJianLi0127")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertTab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe instance);
    partial void UpdateTab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe instance);
    partial void DeleteTab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe instance);
    partial void InsertTab_Excel_ZhengShu(Tab_Excel_ZhengShu instance);
    partial void UpdateTab_Excel_ZhengShu(Tab_Excel_ZhengShu instance);
    partial void DeleteTab_Excel_ZhengShu(Tab_Excel_ZhengShu instance);
    partial void InsertTab_Excel_Company(Tab_Excel_Company instance);
    partial void UpdateTab_Excel_Company(Tab_Excel_Company instance);
    partial void DeleteTab_Excel_Company(Tab_Excel_Company instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::DAL.Properties.Settings.Default.DbJianLi0127ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tab_Excel_Company_User_ZhuanYe> Tab_Excel_Company_User_ZhuanYe
		{
			get
			{
				return this.GetTable<Tab_Excel_Company_User_ZhuanYe>();
			}
		}
		
		public System.Data.Linq.Table<Tab_Excel_ZhengShu> Tab_Excel_ZhengShu
		{
			get
			{
				return this.GetTable<Tab_Excel_ZhengShu>();
			}
		}
		
		public System.Data.Linq.Table<Tab_Excel_Company> Tab_Excel_Company
		{
			get
			{
				return this.GetTable<Tab_Excel_Company>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tab_Excel_Company_User_ZhuanYe")]
	public partial class Tab_Excel_Company_User_ZhuanYe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ecu_ID;
		
		private int _ecu_CompanyId;
		
		private string _ecu_UserName;
		
		private string _ecu_ZhuangYe;
		
		private int _ecu_ZhengShuId;
		
		private System.DateTime _ecu_CreateDate;
		
		private EntityRef<Tab_Excel_ZhengShu> _Tab_Excel_ZhengShu;
		
		private EntityRef<Tab_Excel_Company> _Tab_Excel_Company;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onecu_IDChanging(int value);
    partial void Onecu_IDChanged();
    partial void Onecu_CompanyIdChanging(int value);
    partial void Onecu_CompanyIdChanged();
    partial void Onecu_UserNameChanging(string value);
    partial void Onecu_UserNameChanged();
    partial void Onecu_ZhuangYeChanging(string value);
    partial void Onecu_ZhuangYeChanged();
    partial void Onecu_ZhengShuIdChanging(int value);
    partial void Onecu_ZhengShuIdChanged();
    partial void Onecu_CreateDateChanging(System.DateTime value);
    partial void Onecu_CreateDateChanged();
    #endregion
		
		public Tab_Excel_Company_User_ZhuanYe()
		{
			this._Tab_Excel_ZhengShu = default(EntityRef<Tab_Excel_ZhengShu>);
			this._Tab_Excel_Company = default(EntityRef<Tab_Excel_Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ecu_ID
		{
			get
			{
				return this._ecu_ID;
			}
			set
			{
				if ((this._ecu_ID != value))
				{
					this.Onecu_IDChanging(value);
					this.SendPropertyChanging();
					this._ecu_ID = value;
					this.SendPropertyChanged("ecu_ID");
					this.Onecu_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_CompanyId", DbType="Int NOT NULL")]
		public int ecu_CompanyId
		{
			get
			{
				return this._ecu_CompanyId;
			}
			set
			{
				if ((this._ecu_CompanyId != value))
				{
					if (this._Tab_Excel_Company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onecu_CompanyIdChanging(value);
					this.SendPropertyChanging();
					this._ecu_CompanyId = value;
					this.SendPropertyChanged("ecu_CompanyId");
					this.Onecu_CompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_UserName", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string ecu_UserName
		{
			get
			{
				return this._ecu_UserName;
			}
			set
			{
				if ((this._ecu_UserName != value))
				{
					this.Onecu_UserNameChanging(value);
					this.SendPropertyChanging();
					this._ecu_UserName = value;
					this.SendPropertyChanged("ecu_UserName");
					this.Onecu_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_ZhuangYe", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string ecu_ZhuangYe
		{
			get
			{
				return this._ecu_ZhuangYe;
			}
			set
			{
				if ((this._ecu_ZhuangYe != value))
				{
					this.Onecu_ZhuangYeChanging(value);
					this.SendPropertyChanging();
					this._ecu_ZhuangYe = value;
					this.SendPropertyChanged("ecu_ZhuangYe");
					this.Onecu_ZhuangYeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_ZhengShuId", DbType="Int NOT NULL")]
		public int ecu_ZhengShuId
		{
			get
			{
				return this._ecu_ZhengShuId;
			}
			set
			{
				if ((this._ecu_ZhengShuId != value))
				{
					if (this._Tab_Excel_ZhengShu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onecu_ZhengShuIdChanging(value);
					this.SendPropertyChanging();
					this._ecu_ZhengShuId = value;
					this.SendPropertyChanged("ecu_ZhengShuId");
					this.Onecu_ZhengShuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ecu_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime ecu_CreateDate
		{
			get
			{
				return this._ecu_CreateDate;
			}
			set
			{
				if ((this._ecu_CreateDate != value))
				{
					this.Onecu_CreateDateChanging(value);
					this.SendPropertyChanging();
					this._ecu_CreateDate = value;
					this.SendPropertyChanged("ecu_CreateDate");
					this.Onecu_CreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Excel_ZhengShu_Tab_Excel_Company_User_ZhuanYe", Storage="_Tab_Excel_ZhengShu", ThisKey="ecu_ZhengShuId", OtherKey="ezs_ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tab_Excel_ZhengShu Tab_Excel_ZhengShu
		{
			get
			{
				return this._Tab_Excel_ZhengShu.Entity;
			}
			set
			{
				Tab_Excel_ZhengShu previousValue = this._Tab_Excel_ZhengShu.Entity;
				if (((previousValue != value) 
							|| (this._Tab_Excel_ZhengShu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab_Excel_ZhengShu.Entity = null;
						previousValue.Tab_Excel_Company_User_ZhuanYe.Remove(this);
					}
					this._Tab_Excel_ZhengShu.Entity = value;
					if ((value != null))
					{
						value.Tab_Excel_Company_User_ZhuanYe.Add(this);
						this._ecu_ZhengShuId = value.ezs_ID;
					}
					else
					{
						this._ecu_ZhengShuId = default(int);
					}
					this.SendPropertyChanged("Tab_Excel_ZhengShu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Excel_Company_Tab_Excel_Company_User_ZhuanYe", Storage="_Tab_Excel_Company", ThisKey="ecu_CompanyId", OtherKey="ec_ID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tab_Excel_Company Tab_Excel_Company
		{
			get
			{
				return this._Tab_Excel_Company.Entity;
			}
			set
			{
				Tab_Excel_Company previousValue = this._Tab_Excel_Company.Entity;
				if (((previousValue != value) 
							|| (this._Tab_Excel_Company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tab_Excel_Company.Entity = null;
						previousValue.Tab_Excel_Company_User_ZhuanYe.Remove(this);
					}
					this._Tab_Excel_Company.Entity = value;
					if ((value != null))
					{
						value.Tab_Excel_Company_User_ZhuanYe.Add(this);
						this._ecu_CompanyId = value.ec_ID;
					}
					else
					{
						this._ecu_CompanyId = default(int);
					}
					this.SendPropertyChanged("Tab_Excel_Company");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tab_Excel_ZhengShu")]
	public partial class Tab_Excel_ZhengShu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ezs_ID;
		
		private string _ezs_Name;
		
		private bool _ezs_HaveZhuanYe;
		
		private EntitySet<Tab_Excel_Company_User_ZhuanYe> _Tab_Excel_Company_User_ZhuanYe;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onezs_IDChanging(int value);
    partial void Onezs_IDChanged();
    partial void Onezs_NameChanging(string value);
    partial void Onezs_NameChanged();
    partial void Onezs_HaveZhuanYeChanging(bool value);
    partial void Onezs_HaveZhuanYeChanged();
    #endregion
		
		public Tab_Excel_ZhengShu()
		{
			this._Tab_Excel_Company_User_ZhuanYe = new EntitySet<Tab_Excel_Company_User_ZhuanYe>(new Action<Tab_Excel_Company_User_ZhuanYe>(this.attach_Tab_Excel_Company_User_ZhuanYe), new Action<Tab_Excel_Company_User_ZhuanYe>(this.detach_Tab_Excel_Company_User_ZhuanYe));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ezs_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ezs_ID
		{
			get
			{
				return this._ezs_ID;
			}
			set
			{
				if ((this._ezs_ID != value))
				{
					this.Onezs_IDChanging(value);
					this.SendPropertyChanging();
					this._ezs_ID = value;
					this.SendPropertyChanged("ezs_ID");
					this.Onezs_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ezs_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ezs_Name
		{
			get
			{
				return this._ezs_Name;
			}
			set
			{
				if ((this._ezs_Name != value))
				{
					this.Onezs_NameChanging(value);
					this.SendPropertyChanging();
					this._ezs_Name = value;
					this.SendPropertyChanged("ezs_Name");
					this.Onezs_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ezs_HaveZhuanYe", DbType="Bit NOT NULL")]
		public bool ezs_HaveZhuanYe
		{
			get
			{
				return this._ezs_HaveZhuanYe;
			}
			set
			{
				if ((this._ezs_HaveZhuanYe != value))
				{
					this.Onezs_HaveZhuanYeChanging(value);
					this.SendPropertyChanging();
					this._ezs_HaveZhuanYe = value;
					this.SendPropertyChanged("ezs_HaveZhuanYe");
					this.Onezs_HaveZhuanYeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Excel_ZhengShu_Tab_Excel_Company_User_ZhuanYe", Storage="_Tab_Excel_Company_User_ZhuanYe", ThisKey="ezs_ID", OtherKey="ecu_ZhengShuId")]
		internal EntitySet<Tab_Excel_Company_User_ZhuanYe> Tab_Excel_Company_User_ZhuanYe
		{
			get
			{
				return this._Tab_Excel_Company_User_ZhuanYe;
			}
			set
			{
				this._Tab_Excel_Company_User_ZhuanYe.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Excel_ZhengShu = this;
		}
		
		private void detach_Tab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Excel_ZhengShu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tab_Excel_Company")]
	public partial class Tab_Excel_Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ec_ID;
		
		private string _ec_Name;
		
		private System.Nullable<System.DateTime> _ec_Date;
		
		private EntitySet<Tab_Excel_Company_User_ZhuanYe> _Tab_Excel_Company_User_ZhuanYe;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onec_IDChanging(int value);
    partial void Onec_IDChanged();
    partial void Onec_NameChanging(string value);
    partial void Onec_NameChanged();
    partial void Onec_DateChanging(System.Nullable<System.DateTime> value);
    partial void Onec_DateChanged();
    #endregion
		
		public Tab_Excel_Company()
		{
			this._Tab_Excel_Company_User_ZhuanYe = new EntitySet<Tab_Excel_Company_User_ZhuanYe>(new Action<Tab_Excel_Company_User_ZhuanYe>(this.attach_Tab_Excel_Company_User_ZhuanYe), new Action<Tab_Excel_Company_User_ZhuanYe>(this.detach_Tab_Excel_Company_User_ZhuanYe));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ec_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ec_ID
		{
			get
			{
				return this._ec_ID;
			}
			set
			{
				if ((this._ec_ID != value))
				{
					this.Onec_IDChanging(value);
					this.SendPropertyChanging();
					this._ec_ID = value;
					this.SendPropertyChanged("ec_ID");
					this.Onec_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ec_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ec_Name
		{
			get
			{
				return this._ec_Name;
			}
			set
			{
				if ((this._ec_Name != value))
				{
					this.Onec_NameChanging(value);
					this.SendPropertyChanging();
					this._ec_Name = value;
					this.SendPropertyChanged("ec_Name");
					this.Onec_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ec_Date", DbType="Date")]
		public System.Nullable<System.DateTime> ec_Date
		{
			get
			{
				return this._ec_Date;
			}
			set
			{
				if ((this._ec_Date != value))
				{
					this.Onec_DateChanging(value);
					this.SendPropertyChanging();
					this._ec_Date = value;
					this.SendPropertyChanged("ec_Date");
					this.Onec_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tab_Excel_Company_Tab_Excel_Company_User_ZhuanYe", Storage="_Tab_Excel_Company_User_ZhuanYe", ThisKey="ec_ID", OtherKey="ecu_CompanyId")]
		internal EntitySet<Tab_Excel_Company_User_ZhuanYe> Tab_Excel_Company_User_ZhuanYe
		{
			get
			{
				return this._Tab_Excel_Company_User_ZhuanYe;
			}
			set
			{
				this._Tab_Excel_Company_User_ZhuanYe.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Excel_Company = this;
		}
		
		private void detach_Tab_Excel_Company_User_ZhuanYe(Tab_Excel_Company_User_ZhuanYe entity)
		{
			this.SendPropertyChanging();
			entity.Tab_Excel_Company = null;
		}
	}
}
#pragma warning restore 1591
