//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18063 版自动生成。
// 
#pragma warning disable 1591

namespace DAL.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_ExportExcelSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WebService_ExportExcel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getInitDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback getZhuanYeByZhengShuIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback countFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFilterOperationCompleted;
        
        private System.Threading.SendOrPostCallback countFilter_ForZhengShuOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFilter_ForZhengShuOperationCompleted;
        
        private System.Threading.SendOrPostCallback countCompanyChargerOperationCompleted;
        
        private System.Threading.SendOrPostCallback filterCompanyChargerOperationCompleted;
        
        private System.Threading.SendOrPostCallback addCompanyChargerOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateCompanyChargerOperationCompleted;
        
        private System.Threading.SendOrPostCallback delCompanyChargerOperationCompleted;
        
        private System.Threading.SendOrPostCallback getConnStringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService_ExportExcel() {
            this.Url = global::DAL.Properties.Settings.Default.DAL_localhost_WebService_ExportExcel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getInitDataCompletedEventHandler getInitDataCompleted;
        
        /// <remarks/>
        public event getZhuanYeByZhengShuIdCompletedEventHandler getZhuanYeByZhengShuIdCompleted;
        
        /// <remarks/>
        public event countFilterCompletedEventHandler countFilterCompleted;
        
        /// <remarks/>
        public event getFilterCompletedEventHandler getFilterCompleted;
        
        /// <remarks/>
        public event countFilter_ForZhengShuCompletedEventHandler countFilter_ForZhengShuCompleted;
        
        /// <remarks/>
        public event getFilter_ForZhengShuCompletedEventHandler getFilter_ForZhengShuCompleted;
        
        /// <remarks/>
        public event countCompanyChargerCompletedEventHandler countCompanyChargerCompleted;
        
        /// <remarks/>
        public event filterCompanyChargerCompletedEventHandler filterCompanyChargerCompleted;
        
        /// <remarks/>
        public event addCompanyChargerCompletedEventHandler addCompanyChargerCompleted;
        
        /// <remarks/>
        public event updateCompanyChargerCompletedEventHandler updateCompanyChargerCompleted;
        
        /// <remarks/>
        public event delCompanyChargerCompletedEventHandler delCompanyChargerCompleted;
        
        /// <remarks/>
        public event getConnStringCompletedEventHandler getConnStringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getInitData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getInitData() {
            object[] results = this.Invoke("getInitData", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getInitDataAsync() {
            this.getInitDataAsync(null);
        }
        
        /// <remarks/>
        public void getInitDataAsync(object userState) {
            if ((this.getInitDataOperationCompleted == null)) {
                this.getInitDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInitDataOperationCompleted);
            }
            this.InvokeAsync("getInitData", new object[0], this.getInitDataOperationCompleted, userState);
        }
        
        private void OngetInitDataOperationCompleted(object arg) {
            if ((this.getInitDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInitDataCompleted(this, new getInitDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getZhuanYeByZhengShuId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] getZhuanYeByZhengShuId(int zhengShuId) {
            object[] results = this.Invoke("getZhuanYeByZhengShuId", new object[] {
                        zhengShuId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void getZhuanYeByZhengShuIdAsync(int zhengShuId) {
            this.getZhuanYeByZhengShuIdAsync(zhengShuId, null);
        }
        
        /// <remarks/>
        public void getZhuanYeByZhengShuIdAsync(int zhengShuId, object userState) {
            if ((this.getZhuanYeByZhengShuIdOperationCompleted == null)) {
                this.getZhuanYeByZhengShuIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetZhuanYeByZhengShuIdOperationCompleted);
            }
            this.InvokeAsync("getZhuanYeByZhengShuId", new object[] {
                        zhengShuId}, this.getZhuanYeByZhengShuIdOperationCompleted, userState);
        }
        
        private void OngetZhuanYeByZhengShuIdOperationCompleted(object arg) {
            if ((this.getZhuanYeByZhengShuIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getZhuanYeByZhengShuIdCompleted(this, new getZhuanYeByZhengShuIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countFilter([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr) {
            object[] results = this.Invoke("countFilter", new object[] {
                        companyId,
                        userName,
                        zhengShuArr});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countFilterAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr) {
            this.countFilterAsync(companyId, userName, zhengShuArr, null);
        }
        
        /// <remarks/>
        public void countFilterAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, object userState) {
            if ((this.countFilterOperationCompleted == null)) {
                this.countFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountFilterOperationCompleted);
            }
            this.InvokeAsync("countFilter", new object[] {
                        companyId,
                        userName,
                        zhengShuArr}, this.countFilterOperationCompleted, userState);
        }
        
        private void OncountFilterOperationCompleted(object arg) {
            if ((this.countFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countFilterCompleted(this, new countFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFilter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public excelUserWrapper[] getFilter([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc) {
            object[] results = this.Invoke("getFilter", new object[] {
                        companyId,
                        userName,
                        zhengShuArr,
                        pc});
            return ((excelUserWrapper[])(results[0]));
        }
        
        /// <remarks/>
        public void getFilterAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc) {
            this.getFilterAsync(companyId, userName, zhengShuArr, pc, null);
        }
        
        /// <remarks/>
        public void getFilterAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc, object userState) {
            if ((this.getFilterOperationCompleted == null)) {
                this.getFilterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilterOperationCompleted);
            }
            this.InvokeAsync("getFilter", new object[] {
                        companyId,
                        userName,
                        zhengShuArr,
                        pc}, this.getFilterOperationCompleted, userState);
        }
        
        private void OngetFilterOperationCompleted(object arg) {
            if ((this.getFilterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilterCompleted(this, new getFilterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countFilter_ForZhengShu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countFilter_ForZhengShu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr) {
            object[] results = this.Invoke("countFilter_ForZhengShu", new object[] {
                        companyId,
                        userName,
                        zhengShuArr});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countFilter_ForZhengShuAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr) {
            this.countFilter_ForZhengShuAsync(companyId, userName, zhengShuArr, null);
        }
        
        /// <remarks/>
        public void countFilter_ForZhengShuAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, object userState) {
            if ((this.countFilter_ForZhengShuOperationCompleted == null)) {
                this.countFilter_ForZhengShuOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountFilter_ForZhengShuOperationCompleted);
            }
            this.InvokeAsync("countFilter_ForZhengShu", new object[] {
                        companyId,
                        userName,
                        zhengShuArr}, this.countFilter_ForZhengShuOperationCompleted, userState);
        }
        
        private void OncountFilter_ForZhengShuOperationCompleted(object arg) {
            if ((this.countFilter_ForZhengShuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countFilter_ForZhengShuCompleted(this, new countFilter_ForZhengShuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getFilter_ForZhengShu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object[] getFilter_ForZhengShu([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc) {
            object[] results = this.Invoke("getFilter_ForZhengShu", new object[] {
                        companyId,
                        userName,
                        zhengShuArr,
                        pc});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getFilter_ForZhengShuAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc) {
            this.getFilter_ForZhengShuAsync(companyId, userName, zhengShuArr, pc, null);
        }
        
        /// <remarks/>
        public void getFilter_ForZhengShuAsync(System.Nullable<int> companyId, string userName, keyValueClass[] zhengShuArr, PageClass pc, object userState) {
            if ((this.getFilter_ForZhengShuOperationCompleted == null)) {
                this.getFilter_ForZhengShuOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFilter_ForZhengShuOperationCompleted);
            }
            this.InvokeAsync("getFilter_ForZhengShu", new object[] {
                        companyId,
                        userName,
                        zhengShuArr,
                        pc}, this.getFilter_ForZhengShuOperationCompleted, userState);
        }
        
        private void OngetFilter_ForZhengShuOperationCompleted(object arg) {
            if ((this.getFilter_ForZhengShuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFilter_ForZhengShuCompleted(this, new getFilter_ForZhengShuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/countCompanyCharger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int countCompanyCharger(PageClass pageClass, string where) {
            object[] results = this.Invoke("countCompanyCharger", new object[] {
                        pageClass,
                        where});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void countCompanyChargerAsync(PageClass pageClass, string where) {
            this.countCompanyChargerAsync(pageClass, where, null);
        }
        
        /// <remarks/>
        public void countCompanyChargerAsync(PageClass pageClass, string where, object userState) {
            if ((this.countCompanyChargerOperationCompleted == null)) {
                this.countCompanyChargerOperationCompleted = new System.Threading.SendOrPostCallback(this.OncountCompanyChargerOperationCompleted);
            }
            this.InvokeAsync("countCompanyCharger", new object[] {
                        pageClass,
                        where}, this.countCompanyChargerOperationCompleted, userState);
        }
        
        private void OncountCompanyChargerOperationCompleted(object arg) {
            if ((this.countCompanyChargerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.countCompanyChargerCompleted(this, new countCompanyChargerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/filterCompanyCharger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tab_Excel_Charger[] filterCompanyCharger(PageClass pageClass, string where) {
            object[] results = this.Invoke("filterCompanyCharger", new object[] {
                        pageClass,
                        where});
            return ((Tab_Excel_Charger[])(results[0]));
        }
        
        /// <remarks/>
        public void filterCompanyChargerAsync(PageClass pageClass, string where) {
            this.filterCompanyChargerAsync(pageClass, where, null);
        }
        
        /// <remarks/>
        public void filterCompanyChargerAsync(PageClass pageClass, string where, object userState) {
            if ((this.filterCompanyChargerOperationCompleted == null)) {
                this.filterCompanyChargerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfilterCompanyChargerOperationCompleted);
            }
            this.InvokeAsync("filterCompanyCharger", new object[] {
                        pageClass,
                        where}, this.filterCompanyChargerOperationCompleted, userState);
        }
        
        private void OnfilterCompanyChargerOperationCompleted(object arg) {
            if ((this.filterCompanyChargerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.filterCompanyChargerCompleted(this, new filterCompanyChargerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/addCompanyCharger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tab_Excel_Charger addCompanyCharger(Tab_Excel_Charger obj) {
            object[] results = this.Invoke("addCompanyCharger", new object[] {
                        obj});
            return ((Tab_Excel_Charger)(results[0]));
        }
        
        /// <remarks/>
        public void addCompanyChargerAsync(Tab_Excel_Charger obj) {
            this.addCompanyChargerAsync(obj, null);
        }
        
        /// <remarks/>
        public void addCompanyChargerAsync(Tab_Excel_Charger obj, object userState) {
            if ((this.addCompanyChargerOperationCompleted == null)) {
                this.addCompanyChargerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddCompanyChargerOperationCompleted);
            }
            this.InvokeAsync("addCompanyCharger", new object[] {
                        obj}, this.addCompanyChargerOperationCompleted, userState);
        }
        
        private void OnaddCompanyChargerOperationCompleted(object arg) {
            if ((this.addCompanyChargerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addCompanyChargerCompleted(this, new addCompanyChargerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateCompanyCharger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tab_Excel_Charger updateCompanyCharger(Tab_Excel_Charger obj) {
            object[] results = this.Invoke("updateCompanyCharger", new object[] {
                        obj});
            return ((Tab_Excel_Charger)(results[0]));
        }
        
        /// <remarks/>
        public void updateCompanyChargerAsync(Tab_Excel_Charger obj) {
            this.updateCompanyChargerAsync(obj, null);
        }
        
        /// <remarks/>
        public void updateCompanyChargerAsync(Tab_Excel_Charger obj, object userState) {
            if ((this.updateCompanyChargerOperationCompleted == null)) {
                this.updateCompanyChargerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateCompanyChargerOperationCompleted);
            }
            this.InvokeAsync("updateCompanyCharger", new object[] {
                        obj}, this.updateCompanyChargerOperationCompleted, userState);
        }
        
        private void OnupdateCompanyChargerOperationCompleted(object arg) {
            if ((this.updateCompanyChargerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompanyChargerCompleted(this, new updateCompanyChargerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/delCompanyCharger", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool delCompanyCharger(int id) {
            object[] results = this.Invoke("delCompanyCharger", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void delCompanyChargerAsync(int id) {
            this.delCompanyChargerAsync(id, null);
        }
        
        /// <remarks/>
        public void delCompanyChargerAsync(int id, object userState) {
            if ((this.delCompanyChargerOperationCompleted == null)) {
                this.delCompanyChargerOperationCompleted = new System.Threading.SendOrPostCallback(this.OndelCompanyChargerOperationCompleted);
            }
            this.InvokeAsync("delCompanyCharger", new object[] {
                        id}, this.delCompanyChargerOperationCompleted, userState);
        }
        
        private void OndelCompanyChargerOperationCompleted(object arg) {
            if ((this.delCompanyChargerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delCompanyChargerCompleted(this, new delCompanyChargerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getConnString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getConnString() {
            object[] results = this.Invoke("getConnString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getConnStringAsync() {
            this.getConnStringAsync(null);
        }
        
        /// <remarks/>
        public void getConnStringAsync(object userState) {
            if ((this.getConnStringOperationCompleted == null)) {
                this.getConnStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConnStringOperationCompleted);
            }
            this.InvokeAsync("getConnString", new object[0], this.getConnStringOperationCompleted, userState);
        }
        
        private void OngetConnStringOperationCompleted(object arg) {
            if ((this.getConnStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConnStringCompleted(this, new getConnStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Tab_Excel_Charger {
        
        private int ecr_IDField;
        
        private string ecr_CompanyNameField;
        
        private string ecr_NameField;
        
        private string ecr_ZhiChengField;
        
        private string ecr_BeiZhuField;
        
        /// <remarks/>
        public int ecr_ID {
            get {
                return this.ecr_IDField;
            }
            set {
                this.ecr_IDField = value;
            }
        }
        
        /// <remarks/>
        public string ecr_CompanyName {
            get {
                return this.ecr_CompanyNameField;
            }
            set {
                this.ecr_CompanyNameField = value;
            }
        }
        
        /// <remarks/>
        public string ecr_Name {
            get {
                return this.ecr_NameField;
            }
            set {
                this.ecr_NameField = value;
            }
        }
        
        /// <remarks/>
        public string ecr_ZhiCheng {
            get {
                return this.ecr_ZhiChengField;
            }
            set {
                this.ecr_ZhiChengField = value;
            }
        }
        
        /// <remarks/>
        public string ecr_BeiZhu {
            get {
                return this.ecr_BeiZhuField;
            }
            set {
                this.ecr_BeiZhuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class excelUserWrapper {
        
        private int companyIdField;
        
        private string companyNameField;
        
        private string companyUpdateDateField;
        
        private string userNameField;
        
        private int zhengShuIdField;
        
        private string zhengShuMingField;
        
        private string zhuanYeField;
        
        /// <remarks/>
        public int companyId {
            get {
                return this.companyIdField;
            }
            set {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string companyUpdateDate {
            get {
                return this.companyUpdateDateField;
            }
            set {
                this.companyUpdateDateField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public int zhengShuId {
            get {
                return this.zhengShuIdField;
            }
            set {
                this.zhengShuIdField = value;
            }
        }
        
        /// <remarks/>
        public string zhengShuMing {
            get {
                return this.zhengShuMingField;
            }
            set {
                this.zhengShuMingField = value;
            }
        }
        
        /// <remarks/>
        public string zhuanYe {
            get {
                return this.zhuanYeField;
            }
            set {
                this.zhuanYeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class stringAndStringClass {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PageClass {
        
        private int pageSizeField;
        
        private int currentPageNumberField;
        
        private stringAndStringClass filterField;
        
        private stringAndStringClass orderField;
        
        /// <remarks/>
        public int pageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public int currentPageNumber {
            get {
                return this.currentPageNumberField;
            }
            set {
                this.currentPageNumberField = value;
            }
        }
        
        /// <remarks/>
        public stringAndStringClass filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
            }
        }
        
        /// <remarks/>
        public stringAndStringClass order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class keyValueClass {
        
        private int keyField;
        
        private string valueField;
        
        /// <remarks/>
        public int key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getInitDataCompletedEventHandler(object sender, getInitDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInitDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInitDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getZhuanYeByZhengShuIdCompletedEventHandler(object sender, getZhuanYeByZhengShuIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getZhuanYeByZhengShuIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getZhuanYeByZhengShuIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void countFilterCompletedEventHandler(object sender, countFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getFilterCompletedEventHandler(object sender, getFilterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFilterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFilterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public excelUserWrapper[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((excelUserWrapper[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void countFilter_ForZhengShuCompletedEventHandler(object sender, countFilter_ForZhengShuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countFilter_ForZhengShuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countFilter_ForZhengShuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getFilter_ForZhengShuCompletedEventHandler(object sender, getFilter_ForZhengShuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFilter_ForZhengShuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFilter_ForZhengShuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void countCompanyChargerCompletedEventHandler(object sender, countCompanyChargerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class countCompanyChargerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal countCompanyChargerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void filterCompanyChargerCompletedEventHandler(object sender, filterCompanyChargerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class filterCompanyChargerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal filterCompanyChargerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tab_Excel_Charger[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tab_Excel_Charger[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void addCompanyChargerCompletedEventHandler(object sender, addCompanyChargerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addCompanyChargerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addCompanyChargerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tab_Excel_Charger Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tab_Excel_Charger)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void updateCompanyChargerCompletedEventHandler(object sender, updateCompanyChargerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompanyChargerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompanyChargerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tab_Excel_Charger Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tab_Excel_Charger)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void delCompanyChargerCompletedEventHandler(object sender, delCompanyChargerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class delCompanyChargerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal delCompanyChargerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getConnStringCompletedEventHandler(object sender, getConnStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConnStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConnStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591